<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Footer</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
